<template><view class="page"><view class="profile"><image v-if="avatarUrl" class="avatar" :src="avatarUrl"/><view v-else class="avatar placeholder">{{isLoggedIn?nickname.slice(0,1):'游'}}</view><text class="name">{{isLoggedIn?nickname:'游客用户'}}</text><text class="type">{{isLoggedIn?'微信用户':'已静默登录，授权后可同步资料'}}</text><view v-if="!isLoggedIn" class="login" @tap="authorize">授权微信资料</view></view><view class="section"><view class="section-head"><text>最近充值记录</text><text @tap="goOrders">查看全部 ›</text></view><HmSkeleton v-if="loading" :rows="4"/><HmError v-else-if="error" :text="error" @retry="loadOrders"/><template v-else><view v-for="order in orders" :key="order.id" class="order" @tap="goOrder(order.orderNo)"><view><text class="no hm-mono">{{order.orderNo}}</text><text class="phone hm-mono">{{order.phone}}</text></view><view class="right"><text class="amount hm-mono">¥{{order.cnyPrice}}</text><text :style="{color:statusColor(order.orderStatus)}">{{statusText(order.orderStatus)}}</text></view></view><HmEmpty v-if="!orders.length" text="暂无充值记录"/></template></view><view class="footer"><text @tap="contactService">联系客服</text></view></view></template>
<script setup>
import {ref,computed,onMounted} from 'vue';import {useUserStore} from '@/stores/user';import {userApi,orderApi} from '@/api';import HmEmpty from '@/components/HmEmpty.vue';import HmError from '@/components/HmError.vue';import HmSkeleton from '@/components/HmSkeleton.vue'
const store=useUserStore(),orders=ref([]),loading=ref(true),error=ref('');const isLoggedIn=computed(()=>store.isLoggedIn),nickname=computed(()=>store.userInfo?.nickname||'微信用户'),avatarUrl=computed(()=>store.userInfo?.avatarUrl||'')
async function loadOrders(){loading.value=true;error.value='';try{const r=await orderApi.getMyOrders({page:1,size:3});orders.value=r.data?.records||[]}catch(e){error.value=e.message||'订单加载失败'}finally{loading.value=false}}
async function authorize(){try{const profile=await new Promise((resolve,reject)=>uni.getUserProfile({desc:'用于完善会员资料',success:resolve,fail:reject}));const r=await userApi.updateProfile({nickname:profile.userInfo.nickName,avatarUrl:profile.userInfo.avatarUrl});store.setLogin(r.data);uni.showToast({title:'授权成功',icon:'success'})}catch(e){if(e?.errMsg?.includes('cancel'))return;uni.showToast({title:'授权失败',icon:'none'})}}
function statusColor(s){return {SUCCESS:'#52C41A',SUCCESSFUL:'#52C41A',CHARGING:'#1890FF',PENDING_PAY:'#FAAD14',FAILED:'#FF4D4F',REFUNDED:'#722ED1'}[s]||'#999'}function statusText(s){return {SUCCESS:'成功',SUCCESSFUL:'成功',CHARGING:'充值中',PENDING_PAY:'待支付',FAILED:'异常',REFUNDED:'已退款'}[s]||s}
function goOrders(){uni.navigateTo({url:'/pages/orders/orders'})}function goOrder(no){uni.navigateTo({url:`/pages/result/result?orderNo=${no}&status=processing`})}function contactService(){uni.showToast({title:'请通过小程序客服联系我们',icon:'none'})}
onMounted(async()=>{if(!store.loginReady){try{await store.silentLogin()}catch(e){/* 页面错误态由订单请求呈现 */}}loadOrders()})
</script>
<style scoped>.page{min-height:100vh;background:#F5F7FA;padding-bottom:100rpx}.profile{display:flex;flex-direction:column;align-items:center;background:#fff;padding:56rpx 24rpx}.avatar{width:144rpx;height:144rpx;border-radius:50%}.placeholder{display:flex;align-items:center;justify-content:center;background:#E8EDF3;color:#8291A3;font-size:44rpx}.name{font-size:34rpx;font-weight:600;margin-top:16rpx}.type{font-size:24rpx;color:#999;margin-top:8rpx}.login{margin-top:20rpx;padding:16rpx 36rpx;background:#003366;color:#fff;border-radius:10rpx}.section{padding:24rpx}.section-head{display:flex;justify-content:space-between;margin-bottom:20rpx;font-size:30rpx;font-weight:600}.section-head text:last-child{font-size:24rpx;color:#999;font-weight:400}.order{display:flex;justify-content:space-between;background:#fff;border-radius:12rpx;padding:24rpx;margin-bottom:16rpx}.order>view{display:flex;flex-direction:column;gap:10rpx}.right{align-items:flex-end}.no{font-size:23rpx;color:#999}.phone{font-size:29rpx}.amount{font-size:31rpx;font-weight:700;color:#003366}.footer{position:fixed;bottom:0;left:0;right:0;background:#fff;text-align:center;padding:26rpx;color:#003366}</style>